# Generated by Django 4.2.4 on 2023-08-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('signature', models.CharField(max_length=255)),
                ('inspiration', models.TextField(max_length=1000)),
                ('art_works', models.ImageField(upload_to='')),
            ],
        ),
    ]
