# Generated by Django 4.2.4 on 2023-08-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='art_works',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='inspiration',
            field=models.TextField(max_length=5000),
        ),
    ]
